### ISSUE TITLE
example script gym_test.py is not starting as expected

### ISSUE THREAD

**Issue by lyjbupt** [tawnkramer/gym-donkeycar#32]
* OpenAI Gym Environments for Donkey Carversion:
* Python version: 3.7.7
* Operating System: Ubuntu 18

### Description

Tried to run the example script as below, but it failed.
While when I tried to run donkey_sim.x86_64 directly, it launches OK. Any clue?

### What I Did
(donkey) mypc@ss:~$ python gym_test.py --sim="/home/mypc/work/DonkeySimLinux/donkey_sim.x86_64"
starting DonkeyGym env
donkey subprocess started
Found path: /home/mypc/work/DonkeySimLinux/donkey_sim.x86_64
connecting to 127.0.0.1 9091
Traceback (most recent call last):
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/core/client.py", line 42, in connect
    self.s.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gym_test.py", line 63, in <module>
    env = gym.make(args.env_name, exe_path=args.sim, port=args.port)
  File "/home/mypc/anaconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/mypc/anaconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/mypc/anaconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 136, in __init__
    super(GeneratedTrackEnv, self).__init__(level=3, *args, **kwargs)
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 49, in __init__
    self.viewer = DonkeyUnitySimContoller(level=level, host=host, port=port, cam_resolution=cam_resolution)
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/envs/donkey_sim.py", line 39, in __init__
    self.client = SimClient(self.address, self.handler)
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/core/sim_client.py", line 25, in __init__
    super().__init__(*address)
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/core/client.py", line 33, in __init__
    self.connect()
  File "/home/mypc/work/gym-donkeycar/gym_donkeycar/core/client.py", line 44, in connect
    raise( Exception("Could not connect to server. Is it running? If you specified 'remote', then you must start it manually."))
Exception: Could not connect to server. Is it running? If you specified 'remote', then you must start it manually.
closing donkey sim subprocess

**Comment by lyjbupt** [comment]
After debugging, this issue was caused by limited HW resource. 
I have a patch ready for this, if needed I can submit a PR.
