### ISSUE TITLE
Recent update cause "AttributeError: 'MountainTrackEnv' object has no attribute 'viewer'"

### ISSUE THREAD

**Issue by MengyaoWu1992** [tawnkramer/gym-donkeycar#36]
* OpenAI Gym Environments for Donkey Carversion: gym version 0.17.2 (I am not sure what is this)
* Python version:Python 3.7.7
* Operating System: Ubuntu 18.04

### Description

Install up to date gym-donkey
Run simulator
Get below error:

Traceback (most recent call last):
  File "manage.py", line 644, in <module>
    meta=args['--meta'])
  File "manage.py", line 109, in drive
    cam = DonkeyGymEnv(cfg.DONKEY_SIM_PATH, host=cfg.SIM_HOST, env_name=cfg.DONKEY_GYM_ENV_NAME, conf=cfg.GYM_CONF, delay=cfg.SIM_ARTIFICIAL_LATENCY)
  File "/home/mengyaowu/Desktop/donkeycar/projects/donkeycar/donkeycar/parts/dgym.py", line 25, in __init__
    self.env = gym.make(env_name, exe_path=sim_path, host=host, port=port)
  File "/home/mengyaowu/miniconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/mengyaowu/miniconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/mengyaowu/miniconda3/envs/donkey/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/mengyaowu/Desktop/donkeycar/projects/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 164, in __init__
    super(MountainTrackEnv, self).__init__(level=4, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'exe_path'
Exception ignored in: <function DonkeyEnv.__del__ at 0x7f137550fb90>
Traceback (most recent call last):
  File "/home/mengyaowu/Desktop/donkeycar/projects/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 95, in __del__
    self.close()
  File "/home/mengyaowu/Desktop/donkeycar/projects/gym-donkeycar/gym_donkeycar/envs/donkey_env.py", line 98, in close
    if self.viewer is not None:
AttributeError: 'MountainTrackEnv' object has no attribute 'viewer'

### What I Did

```
I am installing Donkey simulator environment fresh from beginning.
Run with most up to date commit, got above error.
suspected GYM version updated, but it seems there is no update recently.


I randomly checked out previous commit: a421dcc408e4337ba62b8664d0f5c7f31839e6ee 
Running with above commit is working fine

As a result, I suspect recent few commits might have caused some issues.
```

**Comment by tawnkramer** [comment]
things are in transition now. you will need to use the **dev** branch of donkeycar and update your manage.py with ```cd ~/mycar & donkeycar update``` And you will need to build your sim from source. I will have an updated sim binary available in a few days.
