### ISSUE TITLE
unexpected keyword argument 'exe_path'

### ISSUE THREAD

**Issue by RealSEnergy** [tawnkramer/gym-donkeycar#39]
* OpenAI Gym Environments for Donkey Carversion: 1.0.15 (installed from git repo)
* Python version: 3.8.3 (also tried 3.7.6)
* Operating System: Windows 10 

### Description

I tried running example scripts, DDQN.py from examples/reinforcementlearning and some custom test script, everything always resulted in an error with unexpected keyword argument exe_path

### What I Did

```Traceback (most recent call last):
  File "donkey_gym.py", line 17, in <module>
    main();
  File "donkey_gym.py", line 9, in main
    env = gym.make("donkey-warehouse-v0", exe_path=exe_path, port=port)
  File "C:\Users\SEnergy\AppData\Roaming\Python\Python38\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\Users\SEnergy\AppData\Roaming\Python\Python38\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "C:\Users\SEnergy\AppData\Roaming\Python\Python38\site-packages\gym\envs\registration.py", line 60, in make
    env = cls(**_kwargs)
  File "c:\users\senergy\downloads\gym-donkeycar-master\gym-donkeycar-master\gym_donkeycar\envs\donkey_env.py", line 146, in __init__
    super(WarehouseEnv, self).__init__(level=1, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'exe_path'
```

code:

```python
import numpy as np;
import gym
import gym_donkeycar

def main():
	exe_path = "manual"
	port = 9091
	
	env = gym.make("donkey-warehouse-v0", exe_path=exe_path, port=port)
	
	obv = env.reset()
	for t in range(100):
		action = np.array([0.0, 0.25])
		obv, reward, done, info = env.step(action)
	
if __name__ == "__main__":
	main();
```

**Comment by tawnkramer** [comment]
This will need similar changes as gym-test.py to fix.

**Comment by tawnkramer** [comment]
should be fixed now
